name: inner_breeze
description: A meditation and breathing guide app

publish_to: 'none'
 
version: 1.3.1+29

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  english_words: ^4.0.0
  shared_preferences: ^2.2.0
  table_calendar: ^3.0.9
  provider: ^6.0.0
  go_router: ^14.0.2
  syncfusion_flutter_sliders: ^25.1.42 
  window_manager: ^0.3.5
  uuid: ^4.2.2
  intl: ^0.19.0
  url_launcher: ^6.0.0
  just_audio: ^0.9.35
  just_audio_platform_interface: ^4.2.2
  just_audio_cache: ^0.1.2
  audio_session: ^0.1.17
  just_audio_windows: ^0.2.0
  file_picker: ^8.0.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  wakelock_plus: ^1.1.3
  share_plus: ^9.0.0
  document_file_save_plus: ^2.0.0
  package_info_plus: ^8.0.0
  http: ^1.1.2
  fl_chart: ^0.68.0
  just_audio_media_kit: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
    - assets/
    - assets/sounds/
    - assets/images/
    - assets/icons/
